name: Support question
description: Need help with using this package? Ask your question here. Please browse the Discussions for similar questions before.
labels: [question]
body:
  - type: textarea
    attributes:
      label: How can we help?
      description: Please describe what is happening and what you expect to happen.
    validations:
      required: true
